Repository pytroll/satpy, pull requests merged in 2018-07, with the labels that each got.

#353 Fix multiscene memory issues by adding an optional batch_size
  satpy/multiscene.py
Labels: bug

#348 Fix freezing of areas before resampling even as strings
  satpy/resample.py
  satpy/scene.py
Labels: bug, component:resampling

#355 Fix ABI L1B reader losing file variable attributes
  satpy/readers/abi_l1b.py
  satpy/tests/reader_tests/test_abi_l1b.py
Labels: bug, component:readers

#361 Remove Rayleigh correction from abi natural composite
  satpy/etc/composites/abi.yaml
Labels: bug, component:compositors

#362 Replace np.ma.mean by np.nanmean for pixel aggregation
  satpy/composites/__init__.py
  satpy/resample.py
Labels: bug, component:compositors

#339 fixed meteosat native georeferencing
  satpy/readers/native_msg.py
  satpy/tests/reader_tests/test_native_msg.py
Labels: bug, component:readers

#359 Add examples from pytroll-examples to documentation
  doc/source/examples.rst
Labels: documentation
