Repository pytroll/satpy, pull requests merged in 2019-01, with the labels that each got.

#561 Add AHI HRIT B07 files for high resolution night data
  satpy/etc/readers/ahi_hrit.yaml
Labels: component:readers, enhancement

#574 Add code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  README.rst
Labels: documentation

#575 Add page for data download resources
  doc/source/data_download.rst
  doc/source/index.rst
Labels: documentation

#554 Fix AreaDefinition usage to work with newer versions of pyresample
  satpy/readers/geocat.py
  satpy/readers/hrit_jma.py
  satpy/tests/reader_tests/test_utils.py
  satpy/tests/test_multiscene.py
  satpy/tests/test_resample.py
  satpy/tests/test_scene.py
  satpy/tests/writer_tests/test_mitiff.py
  satpy/tests/writer_tests/test_scmi.py
Labels: bug

#585 Fix geotiff writer not using fill_value from writer YAML config
  satpy/tests/writer_tests/test_geotiff.py
  satpy/writers/geotiff.py
Labels: bug

#588 Fix start_time type in seviri_l1b_nc reader
  satpy/readers/seviri_l1b_nc.py
Labels: bug, component:readers

#590 Add FAQ page to docs
  CONTRIBUTING.rst
  doc/source/faq.rst
  doc/source/index.rst
Labels: documentation

#592 Fix masking of AHI HSD space pixels
  satpy/readers/ahi_hsd.py
  satpy/tests/reader_tests/test_ahi_hsd.py
Labels: bug, component:readers, optimization

#594 Fix VIIRS L1B reader not using standard 'y' and 'x' dimension names
  satpy/readers/viirs_l1b.py
Labels: bug, component:readers

#593 Fix sunz_corrected modifier adding unnecessary x and y coordinates
  satpy/composites/__init__.py
  satpy/tests/compositor_tests/__init__.py
Labels: bug, component:compositors

#582 Add 'reduce_data' keyword argument to disable cropping before resampling
  satpy/scene.py
  satpy/tests/test_scene.py
Labels: component:resampling, enhancement

#567 Add utility functions for generating GeoViews plots
  .travis.yml
  doc/source/conf.py
  doc/source/multiscene.rst
  doc/source/quickstart.rst
  satpy/multiscene.py
  satpy/scene.py
  satpy/tests/test_multiscene.py
  satpy/tests/test_scene.py
  setup.py
Labels: enhancement

#600 Fix resample reduce_data bug introduced in #582
  satpy/scene.py
  satpy/tests/test_scene.py
Labels: bug, component:resampling

#602 Fix MultiScene save_animation not using dataset IDs correctly
  satpy/multiscene.py
  satpy/tests/test_multiscene.py
Labels: bug
