Repository pytroll/satpy, pull requests merged in 2019-02, with the labels that each got.

#607 Fix VIIRS 'histogram_dnb' compositor not returning new data
  satpy/composites/viirs.py
  satpy/tests/compositor_tests/test_viirs.py
Labels: bug, component:compositors

#605 Fix enhancements using dask delayed on internal functions
  satpy/enhancements/__init__.py
Labels: bug

#609 Add ability to use dask distributed when generating animation videos
  .travis.yml
  appveyor.yml
  doc/source/multiscene.rst
  satpy/multiscene.py
  satpy/tests/test_multiscene.py
Labels: enhancement, optimization

#614 Support for reduced resolution OLCI data
  satpy/etc/readers/olci_l1b.yaml
Labels: component:readers, enhancement

#613 Add 'crop' and 'save_datasets' to MultiScene
  doc/source/conf.py
  doc/source/dev_guide/xarray_migration.rst
  doc/source/multiscene.rst
  satpy/composites/__init__.py
  satpy/composites/crefl_utils.py
  satpy/multiscene.py
  satpy/readers/electrol_hrit.py
  satpy/readers/goes_imager_hrit.py
  satpy/readers/hrit_jma.py
  satpy/readers/msi_safe.py
  satpy/readers/olci_nc.py
  satpy/readers/sar_c_safe.py
  satpy/readers/slstr_l1b.py
  satpy/resample.py
  satpy/tests/test_multiscene.py
Labels: enhancement

#615 Fix confusing error in abi_l1b reader when file fails to open
  satpy/readers/abi_l1b.py
Labels: bug, component:readers

#616 Fix geotiff writer being unimportable if gdal isn't installed
  satpy/writers/geotiff.py
Labels: bug, component:writers

#621 Add FAQ items on number of workers and threads
  doc/source/faq.rst
Labels: documentation

#627 Add DNB satellite angles (DNB_SENZ, DNB_SENA) to VIIRS SDR reader
  satpy/etc/readers/viirs_sdr.yaml
Labels: component:readers, enhancement

#633 Fix VIIRS HNCC composite passing xarray objects to dask
  .travis.yml
  satpy/composites/viirs.py
  satpy/tests/compositor_tests/test_viirs.py
Labels: bug
