Repository pytroll/satpy, pull requests merged in 2021-09, with the labels that each got.

#1782 Update AGRI/L1 geolocation
  doc/source/conf.py
  satpy/readers/agri_l1.py
  satpy/tests/reader_tests/test_agri_l1.py
Labels: bug, component:readers

#1813 Fix composites failing when inputs are different chunk sizes
  satpy/composites/__init__.py
  satpy/modifiers/_crefl.py
  satpy/tests/modifier_tests/test_crefl.py
  satpy/tests/test_composites.py
Labels: bug, component:compositors

#1819 Fix invalid YAML syntax in enhancement documentation
  doc/source/enhancements.rst
Labels: documentation, component:enhancements

#1817 Fix ninjotiff writer for mode P
  satpy/tests/writer_tests/test_ninjotiff.py
  satpy/writers/ninjotiff.py
Labels: enhancement, component:writers

#1815 Add MODIS L2 products produced by IMAPP
  continuous_integration/environment.yaml
  doc/source/doi_role.py
  satpy/composites/__init__.py
  satpy/etc/readers/modis_l1b.yaml
  satpy/etc/readers/modis_l2.yaml
  satpy/readers/hdfeos_base.py
  satpy/readers/modis_l2.py
  satpy/tests/reader_tests/_modis_fixtures.py
  satpy/tests/reader_tests/conftest.py
  satpy/tests/reader_tests/test_modis_l1b.py
  satpy/tests/reader_tests/test_modis_l2.py
  setup.cfg
  setup.py
Labels: enhancement, component:readers

#1823 Fix unify_chunks usage in compositors and fix image mode in BackgroundCompositor
  satpy/composites/__init__.py
  satpy/tests/test_composites.py
  satpy/tests/test_utils.py
  satpy/utils.py
Labels: bug, component:compositors

#1824 Add additional ACSPO reader file patterns
  satpy/etc/readers/acspo.yaml
  satpy/tests/reader_tests/test_acspo.py
Labels: enhancement, component:readers

#1816 Add 'day_night' flag to DayNightCompositor for day-only or night-only results
  AUTHORS.md
  doc/source/composites.rst
  satpy/composites/__init__.py
  satpy/tests/test_composites.py
Labels: enhancement, component:compositors

#1827 fix eumetsat urls in satpy/readers
  satpy/readers/mviri_l1b_fiduceo_nc.py
  satpy/readers/slstr_l1b.py
  satpy/readers/vii_l1b_nc.py
  satpy/readers/viirs_compact.py
Labels: bug, documentation

#1830 Move tests_require to special "tests" extra for easier installation
  doc/source/dev_guide/index.rst
  pyproject.toml
  satpy/__init__.py
  setup.py
Labels: documentation, cleanup

#1837 Fix config path handling on Windows
  doc/source/config.rst
  doc/source/faq.rst
  satpy/_config.py
  satpy/tests/test_config.py
Labels: bug, documentation
