Repository pytroll/satpy, pull requests merged in 2022-01, with the labels that each got.

#1960 Add release notes and security policy to documentation
  SECURITY.md
  doc/source/index.rst
Labels: documentation

#1961 Update documentation to refer to all EO satellite data
  doc/source/index.rst
Labels: documentation

#1966 Reduce MODIS L1b/L2 test case size for better test performance
  satpy/tests/reader_tests/_modis_fixtures.py
Labels: component:tests

#1967 Add ability to read comma-separated colormaps during enhancement
  satpy/_compat.py
  satpy/enhancements/__init__.py
  satpy/tests/enhancement_tests/test_enhancements.py
Labels: enhancement, component:enhancements

#1962 Use a dependency matrix for benchmarking
  asv.conf.json
Labels: enhancement

#1982 Fix ninjotiff writer from erraneous K to C conversion
  satpy/tests/writer_tests/test_ninjotiff.py
  satpy/writers/ninjotiff.py
Labels: bug

#1988 Update geometry.py docstring from compositor to modifier
  satpy/modifiers/geometry.py
Labels: bug, documentation

#1989 read the "elevation" variable in slstr_l1b
  satpy/etc/readers/slstr_l1b.yaml
Labels: enhancement, component:readers

#1991 Update reference to dask distributed setup page
  doc/source/multiscene.rst
Labels: bug, documentation
