Repository pytroll/satpy, pull requests merged in 2023-09, with the labels that each got.

#2564 Fix floating point edge case in elevation indexing in CREFL
  satpy/modifiers/_crefl_utils.py
Labels: bug, component:compositors

#2509 Add Low Cloud and Fog products to ABI L2 reader
  satpy/etc/enhancements/abi.yaml
  satpy/etc/readers/abi_l2_nc.yaml
  satpy/readers/abi_base.py
  satpy/readers/abi_l2_nc.py
  satpy/tests/reader_tests/test_abi_l2_nc.py
Labels: enhancement, component:readers

#2568 Fix colormap-based tests with new version of trollimage
  satpy/tests/enhancement_tests/test_enhancements.py
  satpy/tests/test_composites.py
Labels: bug, component:enhancements

#2567 Fix readthedocs creating a dirty git environment
  .readthedocs.yml
Labels: documentation, cleanup

#2575 Remove use of deprecated setuptools_scm_git_archive build package
  .github/workflows/deploy-sdist.yaml
  MANIFEST.in
  pyproject.toml
  setup.py
Labels: bug, cleanup

#2578 Remove unneeded performance tracker in seviri reader
  satpy/readers/seviri_l1b_hrit.py
Labels: component:readers, cleanup

#2582 Add mastodon link
  satpy/tests/writer_tests/test_cf.py
  setup.py
Labels: documentation
