Repository pytroll/satpy, pull requests merged in 2023-05, with the labels that each got.

#2456 Fix Adaptive DNB composite bug introduced from refactoring
  satpy/composites/viirs.py
  satpy/tests/compositor_tests/test_viirs.py
Labels: bug, component:compositors

#2453 Fix various warnings encountered when running tests
  doc/source/composites.rst
  doc/source/enhancements.rst
  satpy/_config.py
  satpy/enhancements/__init__.py
  satpy/readers/ami_l1b.py
  satpy/readers/utils.py
  satpy/scene.py
  satpy/tests/compositor_tests/test_spectral.py
  satpy/tests/enhancement_tests/test_enhancements.py
  satpy/tests/multiscene_tests/test_utils.py
  satpy/tests/reader_tests/test_satpy_cf_nc.py
  satpy/tests/reader_tests/test_seviri_l1b_native.py
  satpy/tests/test_config.py
Labels: cleanup

#2472 Add missing test dependencies and update dev environment documentation
  doc/source/dev_guide/index.rst
  setup.py
Labels: bug, documentation, cleanup

#2473 Fix rayleigh correction not handling angles as required inputs
  satpy/modifiers/atmosphere.py
  satpy/tests/test_modifiers.py
Labels: bug, component:compositors

#2449 Generalise the `true_color_reproduction` composite and enhancement
  satpy/enhancements/__init__.py
  satpy/enhancements/ahi.py
  satpy/etc/composites/abi.yaml
  satpy/etc/composites/ahi.yaml
  satpy/etc/composites/ami.yaml
  satpy/etc/composites/fci.yaml
  satpy/etc/enhancements/ahi.yaml
  satpy/etc/enhancements/generic.yaml
  satpy/tests/enhancement_tests/test_ahi.py
  satpy/tests/enhancement_tests/test_enhancements.py
Labels: enhancement, component:compositors

#2480 Add helper-function for reading SEVIRI L1.5 Native header.
  satpy/enhancements/__init__.py
  satpy/readers/seviri_l1b_native.py
  satpy/tests/reader_tests/test_seviri_l1b_native.py
Labels: enhancement, component:readers

#2485 Fix angle caching not handling a specific type of irregular chunking
  satpy/modifiers/angles.py
  satpy/tests/modifier_tests/test_angles.py
Labels: bug, component:compositors

#2492 Fix xarray version for cf tests
  continuous_integration/environment.yaml
  satpy/tests/writer_tests/test_cf.py
Labels: bug

#2491 Change logic for ninjogeotiff gradient/axisintercept tags
  satpy/tests/writer_tests/test_ninjogeotiff.py
  satpy/writers/ninjogeotiff.py
Labels: bug, component:writers
