Repository pytroll/satpy, pull requests merged in 2023-11, with the labels that each got.

#2623 Fix unnecessary Dask `compute()`s in `NDVIHybridGreen` compositor
  satpy/composites/spectral.py
  satpy/tests/compositor_tests/test_spectral.py
Labels: bug, enhancement, component:compositors

#2621 Add resolution-based chunking to ABI L1b reader
  satpy/etc/readers/abi_l1b.yaml
  satpy/readers/abi_base.py
  satpy/readers/abi_l1b.py
  satpy/tests/reader_tests/test_abi_l1b.py
  satpy/utils.py
Labels: enhancement, component:readers, cleanup

#2625 Cleanup various warnings encountered during tests
  doc/source/conf.py
  satpy/readers/abi_l1b.py
  satpy/readers/fci_l1c_nc.py
  satpy/readers/goes_imager_hrit.py
  satpy/readers/hdfeos_base.py
  satpy/readers/mersi_l1b.py
  satpy/readers/utils.py
  satpy/readers/viirs_atms_sdr_base.py
  satpy/tests/modifier_tests/test_parallax.py
  satpy/tests/reader_tests/_li_test_utils.py
  satpy/tests/reader_tests/modis_tests/test_modis_l1b.py
  satpy/tests/reader_tests/test_ami_l1b.py
  satpy/tests/reader_tests/test_gerb_l2_hr_h5.py
  satpy/tests/test_utils.py
  satpy/tests/utils.py
  satpy/tests/writer_tests/test_awips_tiled.py
  satpy/writers/awips_tiled.py
Labels: bug, cleanup

#2627 Fix ABI readers using wrong dtype for resolution-based chunks
  satpy/readers/abi_base.py
  satpy/tests/reader_tests/test_abi_l1b.py
Labels: bug, component:readers

#2634 Remove duplicate entries of required netcdf variables in FCI reader
  satpy/etc/readers/fci_l1c_nc.yaml
Labels: cleanup

#2585 Make caching warn if some of the args are unhashable
  satpy/modifiers/angles.py
  satpy/tests/modifier_tests/test_angles.py
Labels: bug

#2635 Fix nwcsaf_geo start time to be nominal time
  satpy/readers/nwcsaf_nc.py
  satpy/tests/reader_tests/test_nwcsaf_nc.py
Labels: bug, component:readers

#2637 Keep FCI data as 32-bit floats
  satpy/readers/fci_l1c_nc.py
  satpy/tests/reader_tests/test_fci_l1c_nc.py
Labels: enhancement

#2631 Add a reader for MODIS Level 3 files in CMG format.
  satpy/etc/readers/modis_l3.yaml
  satpy/readers/hdfeos_base.py
  satpy/readers/modis_l3.py
  satpy/readers/viirs_edr.py
  satpy/tests/reader_tests/modis_tests/_modis_fixtures.py
  satpy/tests/reader_tests/modis_tests/conftest.py
  satpy/tests/reader_tests/modis_tests/test_modis_l3.py
  satpy/tests/reader_tests/test_viirs_edr.py
Labels: enhancement, component:readers

#2639 Update AVHRR EPS reader to read cloud flags information
  satpy/etc/readers/avhrr_l1b_eps.yaml
  satpy/readers/eps_l1b.py
  satpy/tests/reader_tests/test_eps_l1b.py
Labels: enhancement, component:readers

#2624 Replace assertRaises with pytest.raises
  .pre-commit-config.yaml
  satpy/tests/multiscene_tests/test_save_animation.py
  satpy/tests/reader_tests/test_aapp_mhs_amsub_l1c.py
  satpy/tests/reader_tests/test_ahi_l1b_gridded_bin.py
  satpy/tests/reader_tests/test_ami_l1b.py
  satpy/tests/reader_tests/test_avhrr_l1b_gaclac.py
  satpy/tests/reader_tests/test_clavrx.py
  satpy/tests/reader_tests/test_electrol_hrit.py
  satpy/tests/reader_tests/test_goes_imager_nc_noaa.py
  satpy/tests/reader_tests/test_hrit_base.py
  satpy/tests/reader_tests/test_hy2_scat_l2b_h5.py
  satpy/tests/reader_tests/test_netcdf_utils.py
  satpy/tests/reader_tests/test_scmi.py
  satpy/tests/reader_tests/test_seviri_base.py
  satpy/tests/reader_tests/test_seviri_l1b_calibration.py
  satpy/tests/reader_tests/test_seviri_l1b_icare.py
  satpy/tests/reader_tests/test_utils.py
  satpy/tests/reader_tests/test_vii_base_nc.py
  satpy/tests/reader_tests/test_vii_l1b_nc.py
  satpy/tests/test_composites.py
  satpy/tests/test_dataset.py
  satpy/tests/test_demo.py
  satpy/tests/test_readers.py
  satpy/tests/test_resample.py
  satpy/tests/test_utils.py
  satpy/tests/test_writers.py
  satpy/tests/test_yaml_reader.py
  satpy/tests/writer_tests/test_cf.py
Labels: cleanup

#2642 Set dtype for get_lonlats() in NIR reflectance calculation
  .github/workflows/ci.yaml
  satpy/modifiers/spectral.py
  satpy/tests/test_modifiers.py
Labels: enhancement

#2648 Fix assert_called_once usage in resample tests
  satpy/tests/scene_tests/test_resampling.py
  satpy/tests/writer_tests/test_ninjogeotiff.py
Labels: bug, component:tests, cleanup

#2652 Add file pattern for CRRPh of NWC SAF GEO v2021
  satpy/etc/readers/nwcsaf-geo.yaml
  satpy/tests/reader_tests/test_virr_l1b.py
Labels: enhancement, component:readers

#2641 Add "A" and "D" checks to ruff config
  doc/source/conf.py
  doc/source/doi_role.py
  doc/source/reader_table.py
  pyproject.toml
  satpy/composites/__init__.py
  satpy/composites/abi.py
  satpy/composites/agri.py
  satpy/composites/glm.py
  satpy/dataset/data_dict.py
  satpy/dependency_tree.py
  satpy/enhancements/__init__.py
  satpy/modifiers/_crefl.py
  satpy/modifiers/filters.py
  satpy/modifiers/geometry.py
  satpy/modifiers/parallax.py
  satpy/modifiers/spectral.py
  satpy/multiscene/_multiscene.py
  satpy/readers/__init__.py
  satpy/readers/atms_sdr_hdf5.py
  satpy/readers/avhrr_l1b_gaclac.py
  satpy/readers/file_handlers.py
  satpy/readers/generic_image.py
  satpy/readers/gerb_l2_hr_h5.py
  satpy/readers/ici_l1b_nc.py
  satpy/readers/modis_l3.py
  satpy/readers/mviri_l1b_fiduceo_nc.py
  satpy/readers/nucaps.py
  satpy/readers/scatsat1_l2b.py
  satpy/readers/viirs_edr_active_fires.py
  satpy/readers/viirs_sdr.py
  satpy/readers/xmlformat.py
  satpy/resample.py
  satpy/scene.py
  satpy/tests/modifier_tests/test_parallax.py
  satpy/tests/reader_tests/test_abi_l1b.py
  satpy/tests/reader_tests/test_satpy_cf_nc.py
  satpy/tests/reader_tests/test_viirs_vgac_l1c_nc.py
  satpy/tests/test_node.py
  satpy/tests/test_readers.py
  satpy/writers/awips_tiled.py
  satpy/writers/cf_writer.py
  satpy/writers/geotiff.py
  satpy/writers/ninjogeotiff.py
Labels: cleanup
