Repository pytroll/satpy, pull requests merged in 2024-02, with the labels that each got.

#2731 Remove slstr_l2 reader in favor of ghrsst_l2
  satpy/etc/readers/slstr_l2.yaml
  satpy/readers/__init__.py
Labels: bug, component:readers, backwards-incompatibility

#2597 Update CI to test Python 3.12
  .github/workflows/ci.yaml
Labels: cleanup

#2743 Fix nominal time attributes in SEVIRI HRIT
  satpy/readers/seviri_l1b_hrit.py
  satpy/tests/reader_tests/test_seviri_l1b_hrit_setup.py
Labels: bug, component:readers

#2737 Change `start_time` and `end_time` handling in `combine_metadata`
  satpy/composites/__init__.py
  satpy/dataset/metadata.py
  satpy/multiscene/_blend_funcs.py
  satpy/readers/file_handlers.py
  satpy/tests/multiscene_tests/test_blend.py
  satpy/tests/test_composites.py
  satpy/tests/test_dataset.py
  satpy/tests/test_file_handlers.py
Labels: bug, enhancement, component:compositors

#2744 Fix cutoffs for night_ir_alpha and bump up trollimage version
  continuous_integration/environment.yaml
  satpy/etc/composites/seviri.yaml
  satpy/etc/enhancements/generic.yaml
  setup.py
Labels: enhancement

#2441 Add channel aliases to the CLAVRx reader to facilitate composites
  satpy/etc/enhancements/generic.yaml
  satpy/readers/clavrx.py
  satpy/tests/reader_tests/test_clavrx/__init__.py
  satpy/tests/reader_tests/test_clavrx/test_clavrx_geohdf.py
  satpy/tests/reader_tests/test_clavrx/test_clavrx_nc.py
  satpy/tests/reader_tests/test_clavrx/test_clavrx_polarhdf.py
  satpy/tests/reader_tests/test_clavrx_nc.py
Labels: enhancement, component:readers

#2742 Fix nominal end time in AHI HSD
  satpy/readers/ahi_hsd.py
  satpy/tests/reader_tests/test_ahi_hsd.py
Labels: bug

#2675 Make CF encoding of dataset attributes public
  satpy/cf/attrs.py
  satpy/tests/cf_tests/test_attrs.py
Labels: enhancement

#2745 Sort reader table by name + diverse fixes
  doc/source/_static/main.js
  doc/source/conf.py
  doc/source/dev_guide/custom_reader.rst
  doc/source/index.rst
  satpy/etc/readers/agri_fy4a_l1.yaml
  satpy/etc/readers/agri_fy4b_l1.yaml
  satpy/etc/readers/ghi_l1.yaml
  satpy/etc/readers/meris_nc_sen3.yaml
  satpy/etc/readers/mersi_ll_l1b.yaml
  satpy/etc/readers/sgli_l1b.yaml
  satpy/etc/readers/viirs_compact.yaml
  satpy/etc/readers/viirs_edr.yaml
  satpy/etc/readers/viirs_l1b.yaml
  satpy/etc/readers/viirs_sdr.yaml
Labels: enhancement

#2746 Fix concurrency group in ci
  .github/workflows/ci.yaml
Labels: enhancement

#2720 Add support for the MERSI-RM instrument on FY-3G
  satpy/etc/composites/mersi-rm.yaml
  satpy/etc/readers/mersi_rm_l1b.yaml
  satpy/readers/mersi_l1b.py
  satpy/tests/reader_tests/test_mersi_l1b.py
Labels: enhancement
